
/**
 * Channels all notifications from the sensor observable to the given effector.
 *
 * @param {Rx.Observable} observable the origin observable
 * @param {Rx.Subject} subject the destination effector
 * @return {Rx.Disposable} a disposable generated by a subscribe method
 */
function channel(observable, subject) {
    if (typeof observable === 'undefined') {
        throw new Error('Cannot channel() if sensor is undefined.');
    }
    return observable.subscribe(
        function channelNext(x) {
            subject.onNext(x);
        },
        function channelError(err) {
            console.error(err);
        }
    );
}